# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ministerio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('base', models.CharField(blank=True, choices=[[b'1', 'Adora\xe7\xe3o'], [b'2', 'Servi\xe7o'], [b'3', b'Congregado'], [b'4', b'Discipulado'], [b'5', b'Evangelismo'], [b'6', 'Comunh\xe3o'], [b'7', b'Igreja']], max_length=5, verbose_name='Base')),
            ],
        ),
        migrations.CreateModel(
            name='Participacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('descricao', models.CharField(max_length=200)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cargo')),
                ('ministerio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Ministerio')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_pessoa', models.CharField(blank=True, choices=[[b'1', b'Membro'], [b'2', b'Visitante'], [b'3', b'Congregado'], [b'4', b'Novo decidido'], [b'5', b'Reconciliado'], [b'6', b'Desligado por morte'], [b'7', b'Desligado por abandono'], [b'8', b'Desligado'], [b'9', b'Transferido']], max_length=5, verbose_name='Categoria Pessoa')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email principal')),
                ('data_nascimento', models.DateField()),
                ('data_casamento', models.DateField()),
                ('data_coonversao', models.DateField()),
                ('data_batismo', models.DateField()),
                ('aluno_ebd', models.BooleanField(default=False)),
                ('observacao', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='participacao',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Pessoa'),
        ),
        migrations.AddField(
            model_name='ministerio',
            name='uniadade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Unidade'),
        ),
    ]
